<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Venetas-MacBook-Pro.local" failures="1" tests="3" name="seleniumMavenJUnitStart.seleniumMavenJUnitStart.TNG_0001Test" time="0.058" errors="0" timestamp="2020-10-21T17:00:18 EEST" skipped="1">
  <testcase classname="seleniumMavenJUnitStart.seleniumMavenJUnitStart.TNG_0001Test" name="open_log_in_page_0001" time="0.006"/>
  <system-out/>
  <testcase classname="seleniumMavenJUnitStart.seleniumMavenJUnitStart.TNG_0001Test" name="check_log_in_0001" time="0.052">
    <failure message="expected:&lt;[logged in ]successfull&gt; but was:&lt;[]successfull&gt;" type="org.junit.ComparisonFailure">
      <![CDATA[org.junit.ComparisonFailure: expected:<[logged in ]successfull> but was:<[]successfull>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at seleniumMavenJUnitStart.seleniumMavenJUnitStart.TNG_0001Test.check_log_in_0001(TNG_0001Test.java:14)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- check_log_in_0001 -->
  <system-out/>
  <testcase classname="seleniumMavenJUnitStart.seleniumMavenJUnitStart.TNG_0001Test" name="execute_log_out_0001" time="0.000">
    <skipped/>
  </testcase> <!-- execute_log_out_0001 -->
  <system-out/>
</testsuite> <!-- seleniumMavenJUnitStart.seleniumMavenJUnitStart.TNG_0001Test -->
